//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erudite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstituteDataEntities : DbContext
    {
        public InstituteDataEntities()
            : base("name=InstituteDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Institute> Institutes { get; set; }
        public virtual DbSet<Slot> Slots { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
    }
}
