//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erudite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public int Id { get; set; }
        public int selectedSlot { get; set; }
        public string selectedSubject { get; set; }
        public string selectedSection { get; set; }
        public int selectedSchool { get; set; }
    
        public virtual TeacherBioData TeacherBioData { get; set; }
    }
}
