//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erudite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StaffAndStudentsDataEntities : DbContext
    {
        public StaffAndStudentsDataEntities()
            : base("name=StaffAndStudentsDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<TeacherBioData> TeacherBioDatas { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
    }
}
